name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f q-test/requirements.txt ]; then pip install -r q-test/requirements.txt; fi
    
    - name: Run q-test
      run: |
        python q-test/q-test.py
      env:
        QISKIT_IBM_TOKEN: ${{ secrets.QISKIT_IBM_TOKEN }}